### ISSUE TITLE
KronCov not defined - variance decomposition error

### ISSUE THREAD

**Issue by danielseaton** [limix/limix#4]
I get the following error when running variance decomposition on the cluster from my conda limix_env:

`
Traceback (most recent call last):
  File "protein_variance_decomposition.py", line 60, in <module>
    vc.optimize()
  File "/nfs/software/stegle/users/dseaton/conda-envs/limix_env/lib/python2.7/site-packages/limix/varDecomp/varianceDecomposition.py", line 312, in optimize
    self._initGP()
  File "/nfs/software/stegle/users/dseaton/conda-envs/limix_env/lib/python2.7/site-packages/limix/varDecomp/varianceDecomposition.py", line 513, in _initGP
    for i in range(self.n_randEffs)
NameError: global name 'KronCov' is not defined
`

But when I run it locally on what is a similarly setup conda environment, it works fine.

The script is in /nfs/leia/research/stegle/dseaton/hipsci/variance_decomposition/scripts if you want to try it out.

**Comment by danielseaton** [comment]
I've just had this problem again on a 'fresh' installation of a limix conda environment on my linux laptop. To install, I ran:

` conda install -c conda-forge liknorm`

`pip install liknorm-py`

`pip install limix
`

Package list for conda:

> asciitree                 0.3.3                     <pip>
> backports-abc             0.5                       <pip>
> brent-search              1.0.18                    <pip>
> cachetools                2.0.0                     <pip>
> certifi                   2017.4.17                 <pip>
> cffi                      1.10.0                    <pip>
> click                     6.7                       <pip>
> cloudpickle               0.2.2                     <pip>
> dask                      0.14.3                    <pip>
> distributed               1.16.3                    <pip>
> futures                   3.1.1                     <pip>
> glimix-core               1.2.10                    <pip>
> h5py                      2.7.0                     <pip>
> HeapDict                  1.0.0                     <pip>
> joblib                    0.11                      <pip>
> liknorm                   1.2.6                         2    conda-forge
> liknorm-py                1.0.6                     <pip>
> limix                     1.0.7                     <pip>
> limix-core                1.0.1                     <pip>
> limix-legacy              0.8.12                    <pip>
> locket                    0.2.0                     <pip>
> mkl                       2017.0.1                      0  
> msgpack-python            0.4.8                     <pip>
> ncephes                   1.0.38                    <pip>
> ndarray-listener          1.0.20                    <pip>
> numpy                     1.12.1                   py27_0  
> numpy-sugar               1.0.42                    <pip>
> openssl                   1.0.2l                        0  
> optimix                   1.2.11                    <pip>
> pandas                    0.20.1              np112py27_0  
> pandas-plink              1.2.1                     <pip>
> partd                     0.3.8                     <pip>
> pip                       9.0.1                    py27_1  
> psutil                    5.2.2                     <pip>
> pycparser                 2.17                      <pip>
> python                    2.7.13                        0  
> python-dateutil           2.6.0                    py27_0  
> pytz                      2017.2                   py27_0  
> readline                  6.2                           2  
> scikit-learn              0.18.1                    <pip>
> scipy                     0.19.0                    <pip>
> scipy-sugar               1.0.2                     <pip>
> setuptools                27.2.0                   py27_0  
> singledispatch            3.4.0.3                   <pip>
> six                       1.10.0                   py27_0  
> sortedcollections         0.5.3                     <pip>
> sortedcontainers          1.5.7                     <pip>
> sqlite                    3.13.0                        0  
> tblib                     1.3.2                     <pip>
> tk                        8.5.18                        0  
> toolz                     0.8.2                     <pip>
> tornado                   4.5.1                     <pip>
> tqdm                      4.14.0                    <pip>
> wheel                     0.29.0                   py27_0  
> zict                      0.1.2                     <pip>
> zlib                      1.2.8                         3

**Comment by danielseaton** [comment]
And the packages in my version that is working for variance decomposition, on my laptop - looks like a previous limix?

> appnope                   0.1.0                     <pip>
> asciitree                 0.3.3                     <pip>
> backports-abc             0.5                       <pip>
> backports.shutil-get-terminal-size 1.0.0                     <pip>
> boto3                     1.4.4                     <pip>
> botocore                  1.5.46                    <pip>
> brent-search              1.0.18                    <pip>
> cachetools                2.0.0                     <pip>
> certifi                   2017.4.17                 <pip>
> cffi                      1.10.0                    <pip>
> click                     6.7                       <pip>
> cloudpickle               0.2.2                     <pip>
> cycler                    0.10.0                   py27_0
> dask                      0.14.3                    <pip>
> decorator                 4.0.11                    <pip>
> distributed               1.16.3                    <pip>
> docutils                  0.13.1                    <pip>
> enum34                    1.1.6                     <pip>
> freetype                  2.5.5                         2
> functools32               3.2.3.2                  py27_0
> futures                   3.1.1                     <pip>
> glimix-core               1.2.9                     <pip>
> h5py                      2.7.0                     <pip>
> h5py                      2.7.0               np112py27_0
> hdf5                      1.8.17                        1
> HeapDict                  1.0.0                     <pip>
> icu                       54.1                          0
> ipykernel                 4.6.1                     <pip>
> ipython                   5.3.0                     <pip>
> ipython-genutils          0.2.0                     <pip>
> jmespath                  0.9.2                     <pip>
> joblib                    0.11                      <pip>
> jupyter-client            5.0.1                     <pip>
> jupyter-core              4.3.0                     <pip>
> libpng                    1.6.27                        0
> liknorm                   1.2.3                         1    conda-forge
> liknorm-py                1.0.6                     <pip>
> limix                     1.0.3                     <pip>
> limix-core                1.0.1                     <pip>
> limix-legacy              0.8.12                    <pip>
> locket                    0.2.0                     <pip>
> matplotlib                2.0.1               np112py27_0
> mkl                       2017.0.1                      0
> msgpack-python            0.4.8                     <pip>
> ncephes                   1.0.38                    <pip>
> ndarray-listener          1.0.20                    <pip>
> numexpr                   2.6.2                     <pip>
> numpy                     1.12.1                   py27_0
> numpy-sugar               1.0.41                    <pip>
> openssl                   1.0.2k                        1
> optimix                   1.2.10                    <pip>
> pandas                    0.20.1                    <pip>
> pandas-plink              1.2.1                     <pip>
> partd                     0.3.8                     <pip>
> pathlib2                  2.2.1                     <pip>
> patsy                     0.4.1                    py27_0
> pexpect                   4.2.1                     <pip>
> pickleshare               0.7.4                     <pip>
> pip                       9.0.1                    py27_1
> prompt-toolkit            1.0.14                    <pip>
> psutil                    5.2.2                     <pip>
> ptyprocess                0.5.1                     <pip>
> py                        1.4.33                   py27_0    anaconda
> pycksum                   0.4.2                     <pip>
> pycparser                 2.17                      <pip>
> Pygments                  2.2.0                     <pip>
> pyparsing                 2.1.4                    py27_0
> pyqt                      5.6.0                    py27_2
> pytest                    3.0.7                    py27_0    anaconda
> python                    2.7.13                        0
> python-dateutil           2.6.0                    py27_0
> python-dateutil           2.6.0                     <pip>
> pytz                      2017.2                   py27_0
> pytz                      2017.2                    <pip>
> pyzmq                     16.0.2                    <pip>
> qt                        5.6.2                         0
> readline                  6.2                           2
> s3fs                      0.1.0                     <pip>
> s3transfer                0.1.10                    <pip>
> scandir                   1.5                       <pip>
> scikit-learn              0.18.1                    <pip>
> scipy                     0.19.0                    <pip>
> scipy-sugar               1.0.2                     <pip>
> setuptools                27.2.0                   py27_0
> simplegeneric             0.8.1                     <pip>
> singledispatch            3.4.0.3                   <pip>
> sip                       4.18                     py27_0
> six                       1.10.0                   py27_0
> six                       1.10.0                    <pip>
> sortedcollections         0.5.3                     <pip>
> sortedcontainers          1.5.7                     <pip>
> sqlite                    3.13.0                        0
> subprocess32              3.2.7                    py27_0
> tables                    3.4.2                     <pip>
> tblib                     1.3.2                     <pip>
> tk                        8.5.18                        0
> toolz                     0.8.2                     <pip>
> tornado                   4.5.1                     <pip>
> tqdm                      4.11.2                    <pip>
> traitlets                 4.3.2                     <pip>
> wcwidth                   0.1.7                     <pip>
> wheel                     0.29.0                   py27_0
> zict                      0.1.2                     <pip>
> zlib                      1.2.8                         3
