### ISSUE TITLE
Genotype convert error

### ISSUE THREAD

**Issue by zhaouu** [limix/limix#44]
I can't convert example plink files to limix genotype format.
```
[hzhao@node52 geno_final]$ limix_converter --outfile=./test.hdf5 --plink=/home/hzhao/software/limix-tutorials/data/importer/plink_sample
/home/hzhao/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
limix_conveter.py, Copyright(c) 2014, The LIMIX developers
last modified: Mon May  7 11:17:41 2018
Traceback (most recent call last):
  File "/home/hzhao/bin/limix_converter", line 11, in <module>
    load_entry_point('limix==1.0.17', 'console_scripts', 'limix_converter')()
  File "/home/hzhao/lib/python2.7/site-packages/limix/scripts/limix_converter.py", line 15, in entry_point
    runner.run()
  File "/home/hzhao/lib/python2.7/site-packages/limix_legacy/deprecated/io/conversion.py", line 62, in run
    self.convert_plink(self.hdf,self.options.plink,self.options.chrom,self.options.start,self.options.end)
  File "/home/hzhao/lib/python2.7/site-packages/limix_legacy/deprecated/io/conversion.py", line 204, in convert_plink
    data=PLINK.readBED(bed_file,startpos=startpos,endpos=endpos)
  File "/home/hzhao/lib/python2.7/site-packages/limix_legacy/deprecated/io/plink.py", line 285, in readBED
    SNPs = SP.zeros(((SP.ceil(0.25*N)*4),nSNPs),order=order)
TypeError: 'numpy.float64' object cannot be interpreted as an index
```
And I tried to changed numpy version to 1.11
```
[hzhao@node102 peer]$ pip2 install -U numpy==1.11.0
```
and get a new error:
```
[hzhao@node52 geno_final]$ limix_converter --outfile=./test.hdf5 --plink=/home/hzhao/software/limix-tutorials/data/importer/plink_sample
Traceback (most recent call last):
  File "/home/hzhao/bin/limix_converter", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/hzhao/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3086, in <module>
    @_call_aside
  File "/home/hzhao/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/home/hzhao/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3099, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/hzhao/lib/python2.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/hzhao/lib/python2.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/hzhao/lib/python2.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.11.0 (/home/hzhao/lib/python2.7/site-packages), Requirement.parse('numpy>=1.14.0'), set(['pandas-plink', 'numpy-sugar']))
```
Does anyone know how to solve this problem? Thanks very much!

**Comment by horta** [comment]
Sorry for the delay, @zhaouu . I would recommand using pandas-plink and to work from that, instead of converting to limix format. We want to abolish that format...
