### ISSUE TITLE
Add two random effects in the variance decomposition mode

### ISSUE THREAD

**Issue by Minglc** [limix/limix#46]
Hello, when I add two random effects in the variance decomposition mode, I get the following error,
How can I solve it?

```In [47]: from numpy.random import RandomState
In [48]: from limix.vardec import VarianceDecomposition
In [49]: from numpy import dot, eye, ones
In [50]: from numpy import set_printoptions
In [51]: set_printoptions(4)
In [52]: random = RandomState(1)
In [53]: N = 100
In [54]: P = 1
In [55]: pheno = random.randn(N, P)
In [56]: W = random.randn(N, 10)
In [57]: kinship = dot(W, W.T) / float(10)
In [58]: kinship+= 1e-4*eye(N)
In [59]: Z = random.randn(N, 10)
In [60]: K = dot(Z, Z.T) / float(10)
In [61]: K += 1e-4*eye(N)
In [62]: vc = VarianceDecomposition(pheno)
In [63]: vc.addFixedEffect()
In [64]: vc.addRandomEffect(K=kinship)
In [65]: vc.addRandomEffect(K=K)
In [66]: vc.addRandomEffect(is_noise=True)
In [67]: vc.optimize()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-67-0108efba5822> in <module>()
----> 1 vc.optimize()

/home/hzhao/lib/python2.7/site-packages/limix/vardec/vardec.pyc in optimize(self, init_method, inference, n_times, perturb, pertSize, verbose)
    307 
    308         if self.gp is None:
--> 309             self._initGP()
    310 
    311         params0 = self.gp.getParams()

/home/hzhao/lib/python2.7/site-packages/limix/vardec/vardec.pyc in _initGP(self)
    508             covar = SumCov(*[
    509                 KronCov(self.trait_covars[i], self.sample_covars[i], Iok=Iok)
--> 510                 for i in range(self.n_randEffs)
    511             ])
    512             gp = GP(covar=covar, mean=mean)

NameError: global name 'KronCov' is not defined
```

**Comment by horta** [comment]
Hi @Minglc , I'm implementing it right now on the branch 2.0.0: https://github.com/limix/limix/tree/2.0.0
An example: https://github.com/limix/limix/blob/2.0.0/limix/glmm/test/test_glmm_composer.py

It is preliminary, and I have colegues testing it while I implement. Sorry for the trouble.

**Comment by Minglc** [comment]
thank you for your help，I add the following lines in the _initGP，Is this the right way ?
```
        from limix_core.covar import KronCov
        from limix_core.gp_base import GP
```

**Comment by horta** [comment]
You can give a try... if it works it should be fine.

**Comment by Minglc** [comment]
Thanks a lot. But I still don't know how to use limix to fit a single variant model with two random effect, the limix.qtl.qtl_test_lmm function can just add one kinship matrix. Should I use the VarianceDecomposition to fit this model and then use the log likelihood ration to get the pvalue ?

**Comment by horta** [comment]
I will leave an example and make a easy interface tonigh, then I come back here!

**Comment by rbpisupati** [comment]
Hi, 

I get a ValueError when I add the above lines in the _initGP.

```
Traceback (most recent call last):
    vca.vca_st(args['phenoFile'], args['genoFile'], args['cisregion'], args['kinFile'])
  File "vca.py", line 50, in vca_st
    vc.optimize()
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/limix/vardec/vardec.py", line 323, in optimize
    conv, info = self.gp.optimize(verbose=verbose)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/limix_core/gp/gp_base.py", line 218, in optimize
    opts=opts, *args, **kw_args)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/limix_core/optimize/optimize_bfgs.py", line 129, in opt_hyper
    RV = optimize(f,x,maxfun=int(max_iter),pgtol=pgtol,bounds=bounds,**kw_args)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/scipy/optimize/lbfgsb.py", line 199, in fmin_l_bfgs_b
    **opts)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/scipy/optimize/lbfgsb.py", line 335, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/scipy/optimize/lbfgsb.py", line 285, in func_and_grad
    f = fun(x, *args)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 293, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/limix_core/optimize/optimize_bfgs.py", line 97, in f
    lml_grad = gpr.LML_grad()
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/limix_core/hcache/_hcache.py", line 173, in method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/limix_core/gp/gp_base.py", line 185, in LML_grad
    RV['covar'][i] += 0.5*self.yKiy_grad_i(i)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/limix_core/hcache/_hcache.py", line 173, in method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/limix_core/gp/gp_base.py", line 131, in yKiy_grad_i
    return -(self.Kiy()*self.DiKKiy(i)).sum()
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/numpy/matrixlib/defmatrix.py", line 315, in __rmul__
    return N.dot(other, self)
ValueError: shapes (645,1) and (645,1) not aligned: 1 (dim 1) != 645 (dim 0)
```

Is this problem resolved in new version? 1.0.18?



Rahul

**Comment by horta** [comment]
Not yet. I'm preparing new releases to fix a couple of bugs.

**Comment by horta** [comment]
Please, refer to limix 3.0.0.
