### ISSUE TITLE
AttributeError from liknorm while running glmm

### ISSUE THREAD

**Issue by rbpisupati** [limix/limix#47]
Hi, 

I am getting this error while running glmm with binary traits. Is it something to do with the packages that are installed?

```
Traceback (most recent call last):
  File "lmm.py", line 37, in run_glmm_st
    lmm_chunk = qtl_test_glmm(np.array(snp[:,inputs.accinds], dtype=int).T, np.array(inputs.pheno.values), lik = inputs.pheno_type, K = inputs.kin, test=inputs.test)
  File "/net/gmi.oeaw.ac.at/software/mendel/29_04_2013/software/limix/1.0.12-foss-2017a-Python-2.7.13/lib/python2.7/site-packages/limix-1.0.12-py2.7.egg/limix/qtl/glmm.py", line 95, in qtl_test_glmm
    glmm = GLMM(y, lik, covs, QS)
  File "/net/gmi.oeaw.ac.at/software/mendel/29_04_2013/software/limix/1.0.12-foss-2017a-Python-2.7.13/lib/python2.7/site-packages/glimix_core-1.2.19-py2.7.egg/glimix_core/glmm/glmm.py", line 116, in __init__
    self._machine = LikNormMachine(lik_name, 500)
  File "/net/gmi.oeaw.ac.at/software/mendel/29_04_2013/software/limix/1.0.12-foss-2017a-Python-2.7.13/lib/python2.7/site-packages/liknorm_py-1.0.6-py2.7-linux-x86_64.egg/liknorm/machine.py", line 46, in __init__
    self._lik = getattr(lib, likname.upper())
AttributeError: cffi library 'liknorm._ffi' has no function, constant or global variable named 'BINARY'
```

Rahul

**Comment by horta** [comment]
Hi @rbpisupati , I'm working on this right now. Sorry for the inconvenience...

**Comment by rbpisupati** [comment]
Thanks @horta !

**Comment by horta** [comment]
Hi @rbpisupati , would you mind testing it again? `conda update -c conda-forge limix`

**Comment by rbpisupati** [comment]
Hi, I still get the same error.
Just for the info the below packages got updated.
```
The following packages will be UPDATED:

    brent-search:       1.0.29-py27_0        conda-forge --> 1.0.33-py_1           conda-forge
    glimix-core:        1.2.25-py27_0        conda-forge --> 1.5.2-py27_0          conda-forge
    h5py:               2.7.1-py27_2         conda-forge --> 2.8.0-py27h470a237_0  conda-forge
    joblib:             0.11-py27_0          conda-forge --> 0.12-py_0             conda-forge
    liknorm:            1.3.11-0             conda-forge --> 1.4.6-h470a237_0      conda-forge
    liknorm-py:         1.0.12-py27_0        conda-forge --> 1.1.13-py27h470a237_0 conda-forge
    limix:              1.0.17-py27_0        conda-forge --> 1.0.18-py27_0         conda-forge
    limix-core:         1.0.1-py27_1         conda-forge --> 1.0.2-py_3            conda-forge
    matplotlib:         2.1.0-py27h09aba24_0             --> 2.2.2-py27_1          conda-forge
    ndarray-listener:   1.0.26-py27_0        conda-forge --> 1.1.2-py_1            conda-forge
    optimix:            1.2.21-py27_0        conda-forge --> 2.0.0-py_1            conda-forge
    scipy-sugar:        1.0.4-py27_0         conda-forge --> 1.0.7-py_1            conda-forge

```

**Comment by rbpisupati** [comment]
I am sorry, I am getting a different error now

```
Traceback (most recent call last):
  File "lmm.py", line 37, in run_glmm_st
    lmm_chunk = qtl_test_glmm(np.array(snp[:,inputs.accinds], dtype=int).T, np.array(inputs.pheno.values), lik = inputs.pheno_type, K = inputs.kin, test=inputs.test)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/limix/qtl/glmm.py", line 97, in qtl_test_glmm
    glmm = GLMMExpFam(y, lik, covs, QS)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/glimix_core/glmm/expfam.py", line 86, in __init__
    self._machine = LikNormMachine(self._lik_name, n_int)
  File "/home/GMI/rahul.pisupati/anaconda2/envs/limix/lib/python2.7/site-packages/liknorm/_machine.py", line 52, in __init__
    self._lik = getattr(lib, likname.upper())
AttributeError: cffi library 'liknorm.machine_ffi' has no function, constant or global variable named 'BINARY'

```

**Comment by horta** [comment]
Hum, never seen that error before. Could you try updating some packages? `conda update -c conda-forge liknorm liknorm-py`. After that, could you enter `python -c "import liknorm; print(liknorm.__version__); liknorm.test()"?

**Comment by horta** [comment]
Sorry, just read your previous comment. For some reason you did not get the necessary updated by doing `conda update -c conda-forge limix`. What does `conda search -c conda-forge limix` show?

**Comment by rbpisupati** [comment]
Here, 
```
$ conda search -c conda-forge limix
Loading channels: done
# Name                  Version           Build  Channel             
limix                     0.8.5     np111py27_0  conda-forge         
limix                     0.8.5     np111py35_0  conda-forge         
limix                     0.8.5     np111py36_0  conda-forge         
limix                     0.8.6     np111py27_0  conda-forge         
limix                     0.8.6     np111py35_0  conda-forge         
limix                     0.8.6     np111py36_0  conda-forge         
limix                     1.0.6     np111py27_0  conda-forge         
limix                     1.0.6     np111py35_0  conda-forge         
limix                     1.0.6     np111py36_0  conda-forge         
limix                     1.0.6     np112py27_0  conda-forge         
limix                     1.0.6     np112py35_0  conda-forge         
limix                     1.0.7     np111py27_0  conda-forge         
limix                     1.0.7     np111py35_0  conda-forge         
limix                     1.0.7     np111py36_0  conda-forge         
limix                     1.0.7     np112py27_0  conda-forge         
limix                     1.0.7     np112py35_0  conda-forge         
limix                     1.0.7     np112py36_0  conda-forge         
limix                    1.0.10     np112py27_0  conda-forge         
limix                    1.0.10     np112py35_0  conda-forge         
limix                    1.0.10     np112py36_0  conda-forge         
limix                    1.0.12     np112py27_0  conda-forge         
limix                    1.0.12     np112py35_0  conda-forge         
limix                    1.0.12     np112py36_0  conda-forge         
limix                    1.0.17          py27_0  conda-forge         
limix                    1.0.17          py35_0  conda-forge         
limix                    1.0.17          py36_0  conda-forge         
limix                    1.0.18          py27_0  conda-forge         
limix                    1.0.18          py35_0  conda-forge         
limix                    1.0.18          py36_0  conda-forge         

$ conda search -c conda-forge limix-core
Loading channels: done
# Name                  Version           Build  Channel             
limix-core                1.0.1          py27_0  conda-forge         
limix-core                1.0.1          py27_1  conda-forge         
limix-core                1.0.1          py35_0  conda-forge         
limix-core                1.0.1          py35_1  conda-forge         
limix-core                1.0.1          py36_0  conda-forge         
limix-core                1.0.1          py36_1  conda-forge         
limix-core                1.0.2          py27_1  conda-forge         
limix-core                1.0.2          py35_1  conda-forge         
limix-core                1.0.2          py36_1  conda-forge         
limix-core                1.0.2            py_2  conda-forge         
limix-core                1.0.2            py_3  conda-forge         
```

The git hub repo has also 1.0.18 as the recent version. Isnt it the right version?

**Comment by horta** [comment]
Maybe unistalling limix/liknorm/liknorm-py and installing again solve it (from what I googled)

**Comment by rbpisupati** [comment]
I did try uninstalling all limix, liknorm and liknorm-py and installed it back again. But still I get the same error. I am attaching here all the installed packages in my [conda environment](https://github.com/limix/limix/files/2195288/limix.txt), if it helps.

**Comment by horta** [comment]
In a fresh Ubuntu installation with miniconda2, python 2.7, I did

```
conda config --add channels conda-forge
conda config --add channels bioconda
conda create --name limix --file limix.txt
source activate limix
python -c "import limix; limix.test()"
```

and it worked flawlessly. That is the Dockerfile I used for creating ubuntu with miniconda2:

```
FROM ubuntu:latest
MAINTAINER Danilo Horta

RUN apt-get update --yes
RUN apt-get upgrade --yes
RUN apt-get install git build-essential curl wget cmake --yes
RUN wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
RUN bash Miniconda2-latest-Linux-x86_64.sh -b
RUN rm Miniconda2-latest-Linux-x86_64.sh
ENV PATH="/root/miniconda2/bin:${PATH}"

CMD ["/bin/bash"] 
```

But I think I know what is happening. Have you passed "binary" as the likelihood name? It has to be "bernoulli" or "probit". And actually I should catch that error and print out a more meaninful error...

**Comment by rbpisupati** [comment]
The tests are all successful for me as well..! 
Yes, I was using "binary" as the likelihood name. I also did try it with binomial but ended up with error. Now it is running with bernoulli now. Thanks ..:)))
