### ISSUE TITLE
I installed the stable version using conda but import fails

### ISSUE THREAD

**Issue by jasiozaucha** [limix/limix#86]
The install appeared to be successful. But when I type 'import limix', I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/janzaucha/anaconda3/lib/python3.6/site-packages/limix/__init__.py", line 17, in <module>
    from . import (heritability, io, iset, mtset, plot, qtl, scripts, stats, util,
  File "/Users/janzaucha/anaconda3/lib/python3.6/site-packages/limix/heritability/__init__.py", line 15, in <module>
    from .estimate import estimate
  File "/Users/janzaucha/anaconda3/lib/python3.6/site-packages/limix/heritability/estimate.py", line 6, in <module>
    from glimix_core.glmm import GLMMExpFam
  File "/Users/janzaucha/anaconda3/lib/python3.6/site-packages/glimix_core/__init__.py", line 12, in <module>
    from . import cov, example, ggp, glmm, gp, lik, link, lmm, mean, random
  File "/Users/janzaucha/anaconda3/lib/python3.6/site-packages/glimix_core/cov/__init__.py", line 13, in <module>
    from .sum import SumCov
  File "/Users/janzaucha/anaconda3/lib/python3.6/site-packages/glimix_core/cov/sum.py", line 5, in <module>
    from optimix import FunctionReduce
ImportError: cannot import name 'FunctionReduce'

**Comment by horta** [comment]
I plan to release a new limix version soon fixing but meanwhile please do "pip install glimix-core==2.0.6".

**Comment by jasiozaucha** [comment]
"Successfully installed glimix-core-2.0.6" but problem persists.

**Comment by horta** [comment]
Uninstall the other version. Do "pip uninstall glimix-core" twice just to make sure, then repeat "pip install glimix-core==2.0.6"

**Comment by jasiozaucha** [comment]
After first uninstall I get: ' Successfully uninstalled glimix-core-2.0.6'.
The second uninstall does not seem to do anything, I get 'Skipping glimix-core as it is not installed.'
Then I reinstall and get: 'Successfully installed glimix-core-2.0.6'

But the same problem persists afterwards :(

**Comment by horta** [comment]
Sorry about that, I forgot about another package. Please, do "pip uninstall optimix" and then "pip install optimix==2.0.1".

**Comment by jasiozaucha** [comment]
Awesome, this solves the problem. Many thanks!

**Comment by AmmarMalik93** [comment]
Hi I am getting the following error when I try to "import limix"

  File "<stdin>", line 1, in <module>
  File "/home/ammar/anaconda3/envs/scLVMenv/lib/python2.7/site-packages/limix/__init__.py", line 31, in <module>
    from . import example, glmm, her, io, plot, qc, qtl, sh, stats, threads
  File "/home/ammar/anaconda3/envs/scLVMenv/lib/python2.7/site-packages/limix/sh/__init__.py", line 4, in <module>
    from ._url import download
  File "/home/ammar/anaconda3/envs/scLVMenv/lib/python2.7/site-packages/limix/sh/_url.py", line 24
    f"File {filepath} already exists. Set `force` to `True` in order to\n"
                                                                         ^
SyntaxError: invalid syntax

If I manually edit the code for _url.py by changing ` ` quotes to ' ', and then try to import limix, then I receive following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ammar/anaconda3/envs/scLVMenv/lib/python2.7/site-packages/limix/__init__.py", line 31, in <module>
    from . import example, glmm, her, io, plot, qc, qtl, sh, stats, threads
ImportError: cannot import name example

**Comment by horta** [comment]
That is because you are using python 2.7, which we do not support anymore.
