### ISSUE TITLE
Issues imporing from   limix.stats 

### ISSUE THREAD

**Issue by bader-arouisse** [limix/limix#87]
>>> from limix.stats import linear_kinship
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "limix/__init__.py", line 31, in <module>
    from . import example, glmm, her, io, plot, qc, qtl, sh, stats, threads
  File "limix/sh/__init__.py", line 4, in <module>
    from ._url import download
  File "limix/sh/_url.py", line 24
    f"File {filepath} already exists. Set `force` to `True` in order to\n"
                                                                         ^
SyntaxError: invalid syntax

**Comment by horta** [comment]
This is because limix doest not support python 2.7 anymore.
