### ISSUE TITLE
numpy.linalg.LinAlgError: SVD did not converge

### ISSUE THREAD

**Issue by frankwendt5010** [limix/limix#99]
Limix question forum webpage won't open so posting here:

I have been successfully running the Bayes factor analysis in struct-lmm but now want to run the same analysis on a subset of my data. I created all of the phenotype and environments files in the same way I had done previously (all of which work well). I am now getting the error numpy.linalg.LinAlgError: SVD did not converge and am at a loss for how to fix this. From other threads and wiki pages I started by looking for missing data or NAs and cannot find them in the data or the normalized data. The shape of the data look as expected and none of my environments have 0 variance. I appreciate any help with this.

Traceback:

Traceback (most recent call last):
File "", line 1, in
File "/gpfs/loomis/project/polimanti/frw5/conda_envs/limix_env/lib/python3.7/site-packages/limix/model/struct_lmm/bf.py", line 82, in calc_bf
lml_model_1 = self.calc_lml(self.Env1)
File "/gpfs/loomis/project/polimanti/frw5/conda_envs/limix_env/lib/python3.7/site-packages/limix/model/struct_lmm/bf.py", line 73, in calc_lml
gp = GP2KronSumLR(Y=self.y, F=_covs, A=sp.eye(1), Cn=FreeFormCov(1), G=xoE)
File "/gpfs/loomis/project/polimanti/frw5/conda_envs/limix_env/lib/python3.7/site-packages/limix_core/gp/gp2kronSumLR.py", line 52, in init
covar = Cov2KronSumLR(Cn=Cn, G=G, rank=rank, Cr=Cr)
File "/gpfs/loomis/project/polimanti/frw5/conda_envs/limix_env/lib/python3.7/site-packages/limix_core/covar/cov2kronSumLR.py", line 41, in init
self.G = G
File "/gpfs/loomis/project/polimanti/frw5/conda_envs/limix_env/lib/python3.7/site-packages/limix_core/covar/cov2kronSumLR.py", line 95, in G
_value, U, S, V = svd_reduce(value)
File "/gpfs/loomis/project/polimanti/frw5/conda_envs/limix_env/lib/python3.7/site-packages/limix_core/util/svd_utils.py", line 5, in svd_reduce
U, Sh, V = nla.svd(X, full_matrices=0)
File "<array_function internals>", line 6, in svd
File "/gpfs/loomis/project/polimanti/frw5/conda_envs/limix_env/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 1626, in svd
u, s, vh = gufunc(a, signature=signature, extobj=extobj)
File "/gpfs/loomis/project/polimanti/frw5/conda_envs/limix_env/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 106, in _raise_linalgerror_svd_nonconvergence
raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge

**Comment by horta** [comment]
How are the shapes and min and max values of the provided arrays?

**Comment by frankwendt5010** [comment]
The shapes are all appropriate (I think):

To run the bf command (bf = BF(y, x, F = covs, Env1 = E1, Env2 = E2, W=E1)) comparing a model with environment 1 versus a model with 24 environments (environments 2-25), here are the shapes of my input:
>>> print(x.shape)
(54512, 1)
>>> print(y.shape)
(54512, 1)
>>> print(E1.shape)
(54512, 24)
>>> print(E2.shape)
(54512, 1)


Min and Max:
>>> max(E1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>>> max(E2)
array([5.31659314])
>>> min(E1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
>>> min(E2)
array([-0.63819654])


I'm guessing the error from min/max from E1 is part of my problem here?

**Comment by frankwendt5010** [comment]
Sending an update that I get the same SVD error when calculating OptimalRho for each environments on its own (one environment tested at a time).

**Comment by horta** [comment]
Are you using `numpy.min` and `numpy.max`? You can try to do `print(type(E1))` etc. to know their types because I don't understand why they give these errors...

What is your limix version? `print(limix.__version__)`

**Comment by frankwendt5010** [comment]
Hi Danilo,

I found the issue. I'm not quite sure how it happened but I found that my x variable (the SNP input) was coding a small subset of individuals with nan genotypes. I recreated my plink binary files and this issue seems to be resolved. I am attempting to systematically go through this process again to see if I can find where/how that happened and will post back when I find the error.

I do have a few additional questions: 
(1) to calculate BF for all environments, how do I go about indicating a second model with zero environments against which to test the full model? 
(2) I have started characterizing GxE effects detected from struct-lmm but am curious if BF and optimatlRho for a single environment should be comparable? For example, if a full model has BF = 10 and optimal rho = 0.99 and environment 1 has a BF = 8, should I expect optimal rho for environment 1 to be ~0.8 or are these measurements not comparable in that way? If unrelated, how might one interpret the meaning of (a) high BF and low optimal rho and (b) low BF and high optimal rho. I'm having difficulty wrapping my head around a situation where there is strong GxE evidence from BF analysis but the variance explained is quite low. 

Thanks for your help with this. I appreciate it!

**Comment by horta** [comment]
@rm18 @fpcasale Help, please.

**Comment by frankwendt5010** [comment]
Hi I am following up to see if anyone is able to help with the questions above for BF analyses and interpreting BF-rho information. 

Thanks!
